/**
 * LinkSmart Thing Directory
 * API documetnation of the [LinkSmart Thing Directory](https://github.com/linksmart/thing-directory)
 *
 * The version of the OpenAPI document: 1.0.0-beta.22
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The EventsGet200ResponseInner model module.
 * @module model/EventsGet200ResponseInner
 * @version 1.0.0-beta.22
 */
class EventsGet200ResponseInner {
    /**
     * Constructs a new <code>EventsGet200ResponseInner</code>.
     * @alias module:model/EventsGet200ResponseInner
     * @param id {Number} event id
     * @param event {String} event type
     * @param data {Object} 
     */
    constructor(id, event, data) { 
        
        EventsGet200ResponseInner.initialize(this, id, event, data);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, id, event, data) { 
        obj['id'] = id;
        obj['event'] = event;
        obj['data'] = data;
    }

    /**
     * Constructs a <code>EventsGet200ResponseInner</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/EventsGet200ResponseInner} obj Optional instance to populate.
     * @return {module:model/EventsGet200ResponseInner} The populated <code>EventsGet200ResponseInner</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new EventsGet200ResponseInner();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'Number');
            }
            if (data.hasOwnProperty('event')) {
                obj['event'] = ApiClient.convertToType(data['event'], 'String');
            }
            if (data.hasOwnProperty('data')) {
                obj['data'] = ApiClient.convertToType(data['data'], Object);
            }
        }
        return obj;
    }


}

/**
 * event id
 * @member {Number} id
 */
EventsGet200ResponseInner.prototype['id'] = undefined;

/**
 * event type
 * @member {String} event
 */
EventsGet200ResponseInner.prototype['event'] = undefined;

/**
 * @member {Object} data
 */
EventsGet200ResponseInner.prototype['data'] = undefined;






export default EventsGet200ResponseInner;

