/**
 * LinkSmart Thing Directory
 * API documetnation of the [LinkSmart Thing Directory](https://github.com/linksmart/thing-directory)
 *
 * The version of the OpenAPI document: 1.0.0-beta.22
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The SearchJsonpathGet200ResponseInner model module.
 * @module model/SearchJsonpathGet200ResponseInner
 * @version 1.0.0-beta.22
 */
class SearchJsonpathGet200ResponseInner {
    /**
     * Constructs a new <code>SearchJsonpathGet200ResponseInner</code>.
     * @alias module:model/SearchJsonpathGet200ResponseInner
     */
    constructor() { 
        
        SearchJsonpathGet200ResponseInner.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>SearchJsonpathGet200ResponseInner</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/SearchJsonpathGet200ResponseInner} obj Optional instance to populate.
     * @return {module:model/SearchJsonpathGet200ResponseInner} The populated <code>SearchJsonpathGet200ResponseInner</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new SearchJsonpathGet200ResponseInner();

        }
        return obj;
    }


}






export default SearchJsonpathGet200ResponseInner;

