/**
 * LinkSmart Thing Directory
 * API documetnation of the [LinkSmart Thing Directory](https://github.com/linksmart/thing-directory)
 *
 * The version of the OpenAPI document: 1.0.0-beta.22
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The ValidationErrorAllOfValidationErrors model module.
 * @module model/ValidationErrorAllOfValidationErrors
 * @version 1.0.0-beta.22
 */
class ValidationErrorAllOfValidationErrors {
    /**
     * Constructs a new <code>ValidationErrorAllOfValidationErrors</code>.
     * @alias module:model/ValidationErrorAllOfValidationErrors
     */
    constructor() { 
        
        ValidationErrorAllOfValidationErrors.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>ValidationErrorAllOfValidationErrors</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ValidationErrorAllOfValidationErrors} obj Optional instance to populate.
     * @return {module:model/ValidationErrorAllOfValidationErrors} The populated <code>ValidationErrorAllOfValidationErrors</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ValidationErrorAllOfValidationErrors();

            if (data.hasOwnProperty('field')) {
                obj['field'] = ApiClient.convertToType(data['field'], 'String');
            }
            if (data.hasOwnProperty('description')) {
                obj['description'] = ApiClient.convertToType(data['description'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {String} field
 */
ValidationErrorAllOfValidationErrors.prototype['field'] = undefined;

/**
 * @member {String} description
 */
ValidationErrorAllOfValidationErrors.prototype['description'] = undefined;






export default ValidationErrorAllOfValidationErrors;

