/**
 * LinkSmart Thing Directory
 * API documetnation of the [LinkSmart Thing Directory](https://github.com/linksmart/thing-directory)
 *
 * The version of the OpenAPI document: 1.0.0-beta.22
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from "../ApiClient";
import ProblemDetails from '../model/ProblemDetails';
import ValidationResult from '../model/ValidationResult';

/**
* Validation service.
* @module api/ValidationApi
* @version 1.0.0-beta.22
*/
export default class ValidationApi {

    /**
    * Constructs a new ValidationApi. 
    * @alias module:api/ValidationApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }


    /**
     * Callback function to receive the result of the validationGet operation.
     * @callback module:api/ValidationApi~validationGetCallback
     * @param {String} error Error message, if any.
     * @param {module:model/ValidationResult} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Retrieves the validation result for a given Thing Description
     * The Thing Description should be provided as JSON in the request body.<br> Note: This is currently not supported using Swagger UI. 
     * @param {module:api/ValidationApi~validationGetCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/ValidationResult}
     */
    validationGet(callback) {
      let postBody = null;

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['BasicAuth', 'BearerAuth'];
      let contentTypes = [];
      let accepts = ['application/json', 'application/ld+json'];
      let returnType = ValidationResult;
      return this.apiClient.callApi(
        '/validation', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }


}
